### ISSUE TITLE
Docker compose extra host config needed?

### ISSUE THREAD

**Issue by kedar-1** [jonfairbanks/local-rag#25]
Hello,

I'm running a docker version of the app.
As my ollama is running on host computer as a service I need to add 
 **extra_hosts:
      - 'host.docker.internal:host-gateway'**
 
to docker-compose.yaml file to be able to reach a host ollama using:
**http://host.docker.internal:11434**

Can you add this info to setup.md file?

Thanks

**Comment by jonfairbanks** [comment]
Thanks @kedar-1! I added a note for this in the Readme.
