### ISSUE TITLE
data directory gets destroyed after a pipeline finishes. but is expected to exist by github repo importer

### ISSUE THREAD

**Issue by wolfspyre** [jonfairbanks/local-rag#33]
it seems like after every pass the data directory is deleted... which ... I mean... I wouldn't care perse, except that it causes the github repo process to choke... 

if you set the data directory to undeletable (but still writable) that also causes the app to bark, because it's not permitted to delete the data directory...

so.... if the expectation is that the data directory should be removed at the end of every run... the github process aught expect that it doesn't exist and create it.... not complain, right?

**Comment by jonfairbanks** [comment]
I can take a look at this. The logic might need improved for the repo path.

**Comment by jonfairbanks** [comment]
The GitHub importer has been updated to use the same clean-up logic present in local file/website paths as of the latest release. If you are still experiencing issues with this, please re-open this report or open a new bug report. Thanks!
