### ISSUE TITLE
Error when querying the model

### ISSUE THREAD

**Issue by AusbelDev** [jonfairbanks/local-rag#51]
Hi!
When I run the app and send a query to the model I get the following error:

**ollama - ERROR - Ollama chat stream error: 'HuggingFaceEmbedding' object has no attribute '_model'**

I dont know if this is due to the models I'm using (llama3:instruct, phi3:latest) or a bug caused by the versions of the dependencies.

Hope I can get some help to solve this problem. Ty.

**Comment by jonfairbanks** [comment]
Please checkout the [troubleshooting documentation](https://github.com/jonfairbanks/local-rag/blob/develop/docs/troubleshooting.md). It should help you locate which part of the pipeline is erroring.
