### ISSUE TITLE
AttributeError: 'HuggingFaceEmbedding' object has no attribute '_model'

### ISSUE THREAD

**Issue by JoepdeJong** [jonfairbanks/local-rag#53]
Due to recent updates in `llama_index`, the code breaks when using multiple workers (https://github.com/run-llama/llama_index/issues/13497).

This can be temporary fixed by setting:

```
llama-index = "==0.10.30"
...
llama-index-core = "==0.10.30"
```

In the Pipfile.

**Comment by jonfairbanks** [comment]
Thanks for opening this. I'll also keep an eye on the bug thread as this was definitely working with values >1 before the update.

**Comment by JoepdeJong** [comment]
I did some debugging. It seems that `_model` is missing the second time the `VectorStoreIndex` is used.

This index is initialized here:
https://github.com/jonfairbanks/local-rag/blob/72f2550a22212f5d51fd4dce538ce643a434c98b/utils/llama_index.py#L172

If you debug after this line, or print e.g. the following
```py
print(hasattr(index._embed_model, "_model"))
```
you will see that the model is missing the second time: on file upload it exists, on chat, it isnt there.


It seems to be a problem in the caching:
https://github.com/jonfairbanks/local-rag/blob/72f2550a22212f5d51fd4dce538ce643a434c98b/utils/llama_index.py#L114

After removing `@st.cache_data(show_spinner=False)`, it seems to work again.
