### ISSUE TITLE
Remove the prompt from the response, capitalize first letter of response

### ISSUE THREAD

**Issue by working-name** [jonfairbanks/local-rag#60]
**Is your feature request related to a problem? Please describe.**
I would like to read the answer without the cut-off prompt:

`are a sophisticated virtual assistant designed to assist users in comprehensively understanding and extracting insights from a wide range of documents at their disposal. Your expertise lies in tackling complex inquiries and providing insightful analyses based on the information contained within these documents.`

I would like the first letter of a response to be capitalized, and not cut off the first word (seemingly).

**Describe the solution you'd like**
Hide the service prompt and only display the AI generated response.

Capitalizing the first letter of the response is likely a bug in code rather than what the AI does.

**Describe alternatives you've considered**
Looking at the code, but I'm scared of pythons 😞 

**Additional context**

**Comment by jonfairbanks** [comment]
Can you provide a screenshot of what you're seeing?

**Comment by working-name** [comment]
Sure.

![whatisee](https://github.com/jonfairbanks/local-rag/assets/16505052/ebcd7958-9c6d-4eff-96c6-c6daeda7c81c)

**Comment by jonfairbanks** [comment]
I'll try to track this down sometime this week. This was not occurring previously.

**Comment by jonfairbanks** [comment]
This should be resolved in the latest release. Thanks for the report.
